### ISSUE TITLE
Can no longer see normal pages in WordPress Admin pages "page"

### ISSUE THREAD

**Issue by benfavre** [woocommerce/woocommerce-product-tables-feature-plugin#111] opened 2018-07-18 16:37 UTC
Cannot see existing pages when in WP admin : /wp-admin/edit.php?post_type=page
Version : 4.9.7
Multisite: Yes

**Comment by kloon** [comment] 2018-07-19 12:16
@benfavre enable WP_DEBUG and check your error log. Let me know what it says.

**Comment by benfavre** [comment] 2018-07-20 16:42
![image](https://user-images.githubusercontent.com/664679/43014527-b019faf0-8c4c-11e8-99e1-316546e91102.png)

**Comment by benfavre** [comment] 2018-07-20 16:42
There are no errors

**Comment by benfavre** [comment] 2018-07-20 17:18
Now I have managed to install the plugin by fixing issue #113 I can see this problem is a more general one : 
![image](https://user-images.githubusercontent.com/664679/43016007-a80e4c62-8c51-11e8-921c-cce4035c1011.png)

**Comment by kloon** [comment] 2018-07-30 13:03
@benfavre so this issue goes away once you have the version with the fixes I implemented in e791d36?

**Comment by benfavre** [comment] 2018-07-30 13:19
No.
If I had to guess, the plugin is modifying the query/or the object thats used by the table.

Note:
The number of posts (7) in my case is correct for the "page" post type for that site.

**Comment by rodrigoprimo** [comment] 2018-08-09 14:12
I'm not able to reproduce this issue as well. Both pages and product variations as displayed as expected. @benfavre, could you maybe test using another database to see if you can reproduce? Would you be able to provide steps for us to reproduce your issue? Thanks.

**Comment by mgollmer** [comment] 2018-09-28 09:49
I have the same issue. I'm not able to see pages or products in admin and frontend. I installed a fresh wordpress and woocommerce 3.5 beta.

**Comment by mgollmer** [comment] 2018-09-28 09:55
#113 fixing the issue  for me;)

**Comment by kloon** [comment] 2018-09-29 15:40
Closing, this was fixed in https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/commit/e791d366b4db5093e28711c0dacc503108718ab6

**Closed by kloon** 2018-09-29 15:40 UTC
Labels: Status: Needs Author Feedback
