### ISSUE TITLE
the plugin erase images of products and no delete all meta

### ISSUE THREAD

**Issue by Japsus** [woocommerce/woocommerce-product-tables-feature-plugin#136] opened 2018-11-01 20:25 UTC
----------------My Server-----------------
Distribution: Ubuntu 18.04.1 LTS
Wordpress Version: 4.9.8
Woocommerce Version: 3.5.1
Nginx Version: 1.14.0 
PHP Version: PHP 7.2.10
MySQL Version: Ver 14.14, Distrib 5.7.24.
--------------------------------------------
Issue:

When I make the insertion of the products using the code: "wp wc-product-tables migrate-data" the images of the products are lost and they are no longer displayed in the store.

before:

![image](https://user-images.githubusercontent.com/37185842/47877623-9c727f00-de1c-11e8-94c8-92783f7818ee.png)

after:

![image](https://user-images.githubusercontent.com/37185842/47877587-8d8bcc80-de1c-11e8-95ac-9fc046121966.png)

if I release the code "wp wc-product-tables migrate -data [--clean-old-data] "also does not eliminate many of the metas of the products and therefore does not lower the meta table so the performance of the web is still low.

**Comment by leewillis77** [comment] 2018-11-02 16:10
The missing images looks like a duplicate of #124 

For the lingering meta items, can you provide a list of which meta items aren't removed?

**Comment by Japsus** [comment] 2018-11-05 12:54
> The missing images looks like a duplicate of #124
> 
> For the lingering meta items, can you provide a list of which meta items aren't removed?

Yes, but mi version de woocommerce is the 3.5.1, and this solution (#124) is already implemented in that version, and i can't see the images.

And this are the meta items aren't removed:

![image](https://user-images.githubusercontent.com/37185842/47999081-aee10700-e101-11e8-9f77-fc95a8dd0e6c.png)

LIST:
'__is_newly_created_product',
'_backorders',
'_crosssell_ids',
'_default_attributes',
'_download_expiry',
'_download_limit',
'_downloadable',
'_height',
'_length',
'_manage_stock',
'_price',
'_product_attributes',
'_product_image_gallery',
'_product_version',
'_purchase_note',
'_regular_price',
'_sale_price',
'_sale_price_dates_from',
'_sale_price_dates_to',
'_sku',
'_sold_individually',
'_stock',
'_stock_status',
'_tax_class',
'_tax_status',
'_thumbnail_id',
'_upsell_ids',
'_virtual',
'_wc_average_rating',
'_wc_rating_count',
'_wc_review_count',
'_weight',
'_width',
'_wp_page_template',
'total_sales',
'upc',

**Comment by claudiosanches** [comment] 2019-09-03 21:59
> When I make the insertion of the products using the code: "wp wc-product-tables migrate-data" the images of the products are lost and they are no longer displayed in the store.

This command alone isn't able to remove any meta data, you should try `wp wc-product-tables migrate-data --clean-old-data`, but note that you can only run this command one time, since may generate empty data since is already migrated and removed.

About the image issue I have made a few improvements on it, and should work now.

> And this are the meta items aren't removed:

You are listing also meta data from WordPress, 3rd party plugins and even data that we should still keep as meta data.
You can see what is migrated in:

https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/blob/50d2cc25f103962ec7a886b73eb33b1e04785726/includes/class-wc-product-tables-migrate-data.php#L14-L54

I just made a test with `wp wc-product-tables migrate-data --clean-old-data`, and it's works just fine, cleaning the database.

**Closed by claudiosanches** 2019-09-03 21:59 UTC
